development:
  password: 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
  theme_id: 125092855957
  store: ean-astro-practice.myshopify.com
  timeout: 60s
  ignores:
    - themekit_ignores

production:
  password: 
  theme_id:
  store:
  timeout: 60s
  readonly: true
  ignores:
    - themekit_ignores